import {IPayment} from '../interfaces/IPayment';

export const categories: IPayment[] = [
  { keyword: "מזון ומשקאות",  translation: "food",        icon: "shopping_cart" },
  { keyword: "מזון וצריכה",   translation: "food",        icon: "shopping_cart" },
  { keyword: "מסעדות",        translation: "restaurants", icon: "restaurant" },
  { keyword: "מזון מהיר",        translation: "fast food", icon: "restaurant" },
  { keyword: "ציוד ומשרד",    translation: "service fee", icon: "paid" },
  { keyword: "פנאי בילוי",    translation: "entertainment", icon: "local_play" },
  { keyword: "משחקי מזל",     translation: "entertainment", icon: "casino" },
  { keyword: "פנאי ובידור",   translation: "entertainment", icon: "casino" },
  { keyword: "חינוך",   translation: "education", icon: "school" },
  { keyword: "תיירות",       translation: "tourism", icon: "airplane_ticket" },
  { keyword: "רפואה ובריאות", translation: "health",        icon: "local_hospital" },
  { keyword: "טיפוח ויופי", translation: "care and beauty", icon: "spa" },
  { keyword: "תקשורת ומחשבים", translation: "communication and computers", icon: "computer" },
  { keyword: "ריהוט ובית",    translation: "household",     icon: "home" },
  { keyword: "ילדים",         translation: "child",         icon: "child_friendly" },
  { keyword: "ביטוח ופיננסים", translation: "insurance",    icon: "admin_panel_settings" },
  { keyword: "פיננסים",       translation: "finance services", icon: "attach_money" },
  { keyword: "פיננסים",        translation: "money transfer", icon: "send" },
  { keyword: "מלונאות ואירוח",  translation: "hotels", icon: "hotel" },
  { keyword: "אופנה",       translation: "clothes", icon: "checkroom" },
  { keyword: "סטימצקי",       translation: "clothes", icon: "checkroom" },
  { keyword: "הלבשה והנעלה",       translation: "clothes", icon: "checkroom" },
  { keyword: "שונות",       translation: "other", icon: "grain" },
  { keyword: "coffee",       translation: "coffee", icon: "coffee" },
  { keyword: "pet",         translation: "pet", icon: "pets" },
  { keyword: "רכב ותחבורה",  translation: "transport", icon: "airport_shuttle" },
  { keyword: "מוסדות",  translation: "institutions", icon: "account_balance" },
  { keyword: "עירייה וממשלה",  translation: "institutions", icon: "account_balance" },
  { keyword: "עמותות ותרומות",  translation: "donation", icon: "volunteer_activism" },
];
